line_591_notifications/urls.py
from django.contrib import admin
from django.urls import path
from . import views
import line_591_notifications.api as api
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.homepage),
    path("login/", views.login),
    path('isLogin/', views.isLogin),
    path('isLogout/', views.isLogout),
    path('isAuth/', views.isAuth),
    path('isDone/', views.isDone),
    path("auth/", api.auth),
    path("test", api.test),
]

line_591_notifications/models.py
from django.db import models
import uuid

class User(models.Model):
    id = models.CharField(primary_key=True, max_length=255)

class Notification(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=100)
    token = models.CharField(max_length=100)
    rent_url = models.CharField(max_length=1000)
    
# class RentCondition(models.Model):
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     notification = models.ForeignKey(Notification, on_delete=models.CASCADE)
    # url = models.URLField() # TODO: remove this field later

line_591_notifications/forms.py
from django import forms
from .models import Notification

class NotifyForm(forms.ModelForm):
    class Meta:
        model = Notification
        fields = ('user', 'code', 'rent_url', )

line_591_notifications/views.py
import os, json
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect
from urllib.parse import parse_qs
import line_591_notifications.CONST as CONST
import line_591_notifications.utils as utils
import line_591_notifications.forms as forms
import line_591_notifications.models as models
import line_591_notifications.api as api

from dotenv import load_dotenv
load_dotenv()

def homepage(request: HttpRequest):
    context = { 
        "auth_url": CONST.AUTHORIZE_URL,
        "auth_redirect_url": CONST.BASE_URL + "/isAuth/",
        "client_id": os.environ.get("client_id"),
        "response_type": "code",
        "scope": "notify",
        "state": utils.generate_csrf_token(),
    }

    return render(request, 'homepage.html', context)

def login(request: HttpRequest):
    context = {
        "login_url": CONST.LOGIN_URL,
        "login_id": os.environ.get("login_id"),
        "scope": "openid", 
        "redirect_url": CONST.BASE_URL + "/isLogin/",
        "response_type": "code",
        "state": utils.generate_csrf_token(),
    }

    return render(request, 'login.html', context)

def isLogin(request: HttpRequest):
    try:
        res = api.login(request).content
        data = json.loads(res.decode("utf-8"))
        if data["user_id"]:
            context = {"user_id": data["user_id"]}
            return render(request, 'isLogin.html', context)
        else:
            return redirect("/")
    except Exception as e:
        return redirect("/")

def isLogout(request: HttpRequest):
    return render(request, 'isLogout.html')

def isAuth(request: HttpRequest):
    try:
        context = {
            "base_url": CONST.BASE_URL,
            "form": forms.NotifyForm(),
            "notify_code": request.GET["code"],
        }

        if request.method == 'POST':
            res = api.auth(request)
            if res.status_code == 200:
                return HttpResponse("Done", status=200)
            else:
                return HttpResponse("Expired", status=400)
                
    except Exception as e:
        return redirect("/")
    return render(request, 'isAuth.html', context)

def isDone(request: HttpRequest):
    return render(request, 'isDone.html')

line_591_notifications/templates/homepage.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redirect Button</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% load static %}
</head>

<script>
    function checkUserId() {
        const userId = localStorage.getItem('userId');
        if (!userId) {
            window.location.href = '/login';
        }
    }
    setInterval(checkUserId, 100);
</script>

<script>
    function logout() {
        localStorage.removeItem('userId');
        window.location.href = "{{base_url}}/isLogout";
    }
    function auth() {
        let url = `{{auth_url}}?response_type={{response_type}}&client_id={{client_id}}&redirect_uri={{auth_redirect_url}}&scope={{scope}}&state={{state}}`;
        window.location.href = url;
    }
</script>

<body>
<section class="bg-primary py-3 py-md-5 py-xl-8">
    <div class="container">
      <div class="row gy-4 align-items-center">
        <div class="col-12 col-md-6 col-xl-7">
          <div class="d-flex justify-content-center text-bg-primary">
            <div class="col-12 col-xl-9">
              <hr class="border-primary-subtle mb-4">
              <h1 class="h1 mb-4">591 房源即時通知</h1>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 col-xl-5">
          <div class="card border-0 rounded-4">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <div class="row">
                <div class="col-12">
                  <div class="mb-4">
                    <h3>綁定 Line Notify</h3>
                  </div>
                </div>
              </div>
              <div class="row gy-3 overflow-hidden">
                  <div class="col-12">
                    <div class="d-grid">
                        <button onclick=auth() class="btn btn-primary btn-lg">開始綁定</button>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="d-grid">
                        <button onclick=logout() class="btn btn-primary btn-lg">登出</button>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
		<div class="col-12 col-md-6 col-xl-5 text-bg-primary">
			<div class="text-endx">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-grip-horizontal" viewBox="0 0 16 16">
                  <path d="M2 8a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg>
              </div>
		</div>

    <!-- Remove the container if you want to extend the Footer to full width. -->
    <footer class="text-center text-lg-start text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">  
        <hr class="mb-4" />
        <!-- Section: Social media -->
        <section class="mb-4 text-center"> 
        <!-- Google -->
        <a
            class="btn btn-outline-light btn-floating m-1"
            href="mailto:r11323007@ntu.edu.tw"
            role="button"
            ><i class="fa fa-google"></i
            ></a>

        <!-- Github -->
        <a
            class="btn btn-outline-light btn-floating m-1"
            href="https://github.com/johnny890122/line_591_notifications" 
            target="_blank"
            role="button"
            ><i class="fa fa-github"></i
            ></a>
        </section>
    </div>
    </footer>
    </div>
</section>

</body>
</html>

line_591_notifications/templates/isAuth.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<script>
  function checkUserId() {
      const userId = localStorage.getItem('userId');
      if (!userId) {
          window.location.href = '/login';
      }
  }
  setInterval(checkUserId, 100);
</script>

<script>
    $(document).ready(function() {
        $('#id_user').val(localStorage.getItem('userId'));

        $('#submitButton').on('click', function(event) {
            event.preventDefault(); // Prevent the default form submission
            const urlInput = document.getElementById('id_rent_url').value;
            const messageElement = document.getElementById('message');

            // Regular expression for validating URL
            const urlPattern = new RegExp('^(https?:\\/\\/)' + // protocol
              '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.?)+[a-z]{2,}|' + // domain name
              '((\\d{1,3}\\.){3}\\d{1,3}))' + // OR ip (v4) address
              '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*' + // port and path
              '(\\?[;&a-z\\d%_.~+=,\\-]*)?' + // query string (updated to allow commas and hyphens)
              '(\\#[-a-z\\d_]*)?$', 'i'); // fragment locator

            if (!urlPattern.test(urlInput)) {
                messageElement.textContent = '無效的網址';
                messageElement.style.color = 'red';
                return;
            }

            // Checking URL prefix
            const allowedPrefixes = ['http://', 'https://'];
            const isPrefixValid = allowedPrefixes.some(prefix => urlInput.startsWith(prefix));

            if (!isPrefixValid) {
                messageElement.textContent = 'URL must start with http:// or https://';
                messageElement.style.color = 'red';
                return;
            }

            messageElement.textContent = 'Valid URL';
            messageElement.style.color = 'green';

            var formData = $('#form').serialize(); // Serialize the form data

            $.post($('#form').attr('action'), formData, function(response) {
              if (response == "Done") {
                window.location.href = "{{base_url}}/isDone";
              } else if (response == "Expired"){
                alert("授權碼已過期，請重新綁定 Line Notify。");
                window.location.href = "{{base_url}}/isLogin";
              }
            }).fail(function() {
                alert('請重新登入。');
                window.location.href = "{{base_url}}/login";
            });
        });
    });
</script>

<body>
<section class="bg-primary py-3 py-md-5 py-xl-8">
    <div class="container">
      <div class="row gy-4 align-items-center">
        <div class="col-12 col-md-6 col-xl-7">
          <div class="d-flex justify-content-center text-bg-primary">
            <div class="col-12 col-xl-9">
              <hr class="border-primary-subtle mb-4">
              <h1 class="h1 mb-4">591 房源即時通知</h1>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 col-xl-5">
          <div class="card border-0 rounded-4">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <div class="row">
                <div class="col-12">
                  <div class="mb-4">
                    <h3>輸入 591 租屋資訊</h3>
                  </div>
                </div>
              </div>
              <div class="row gy-3 overflow-hidden">
                  <div class="col-12">
                    <div class="d-grid">
                      <form id="form" method="post">    
                        {% csrf_token %}
                        <input id="id_user" name="user" value="" style="display: none;">   
                        <input id="id_code" name="code" value='{{notify_code}}' style="display: none;"> 
                        <!-- <div id="urlInput" contenteditable="true" style="border: 1px solid #ccc; padding: 5px;"></div> -->
                        <input required id="id_rent_url" class="form-control" name="rent_url" rows="5" value=""></input> 
                      </form>
                    </div>
                    <div class="mb-4">
                      <p id="message"></p>
                    </div>
                    <div class="d-grid">
                        <button id="submitButton" class="btn btn-primary btn-lg" type="submit">提交</button>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
		<div class="col-12 col-md-6 col-xl-5 text-bg-primary">
			<div class="text-endx">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-grip-horizontal" viewBox="0 0 16 16">
                  <path d="M2 8a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg>
              </div>
		</div>

    <!-- Remove the container if you want to extend the Footer to full width. -->
    <footer class="text-center text-lg-start text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">  
        <hr class="mb-4" />
        <!-- Section: Social media -->
        <section class="mb-4 text-center"> 
        <!-- Google -->
        <a
            class="btn btn-outline-light btn-floating m-1"
            href="mailto:r11323007@ntu.edu.tw"
            role="button"
            ><i class="fa fa-google"></i
            ></a>

        <!-- Github -->
        <a
            class="btn btn-outline-light btn-floating m-1"
            href="https://github.com/johnny890122/line_591_notifications" 
            target="_blank"
            role="button"
            ><i class="fa fa-github"></i
            ></a>
        </section>
    </div>
    </footer>
    </div>
</section>
</body>
</html>

line_591_notifications/templates/isDone.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% load static %}
</head>

<script>
    localStorage.removeItem('userId');
</script>

<section class="bg-primary py-3 py-md-5 py-xl-8">
    <div class="container">
      <div class="row gy-4 align-items-center">
        <div class="col-12 col-md-6 col-xl-7">
          <div class="d-flex justify-content-center text-bg-primary">
            <div class="col-12 col-xl-9">
              <hr class="border-primary-subtle mb-4">
              <h1 class="h1 mb-4">591 房源即時通知</h1>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 col-xl-5">
          <div class="card border-0 rounded-4">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <div class="row">
                <div class="col-12">
                  <div class="mb-4">
                    <h3>完成綁定</h3>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="mb-4">
                    <p>已成功綁定，請關閉本頁面。</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
		<div class="col-12 col-md-6 col-xl-5 text-bg-primary">
			<div class="text-endx">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-grip-horizontal" viewBox="0 0 16 16">
                  <path d="M2 8a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg>
              </div>
		</div>

    <!-- Remove the container if you want to extend the Footer to full width. -->
    <footer class="text-center text-lg-start text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">  
        <hr class="mb-4" />
        <div class="container p-4 pb-0">  
            <img class="img-fluid rounded mb-4" loading="lazy" src="{% static 'success.png' %}">
        </div>
        <!-- Section: Social media -->
        <section class="mb-4 text-center"> 
        <!-- Google -->
        <a
            class="btn btn-outline-light btn-floating m-1"
            href="mailto:r11323007@ntu.edu.tw"
            role="button"
            ><i class="fa fa-google"></i
            ></a>

        <!-- Github -->
        <a
            class="btn btn-outline-light btn-floating m-1"
            href="https://github.com/johnny890122/line_591_notifications" 
            target="_blank"
            role="button"
            ><i class="fa fa-github"></i
            ></a>
        </section>
    </div>
    </footer>
    </div>
</section>
</body>

</html>

line_591_notifications/templates/isLogin.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% load static %}
</head>

<script>
  function checkUserId() {
      const userId = localStorage.getItem('userId');
      if (!userId) {
          window.location.href = '/login';
      }
  }
  setInterval(checkUserId, 100);
</script>

<script>
    localStorage.setItem('userId', '{{user_id}}');
    function backToHome() {
        window.location.href = "{{base_url}}/"
    }

    // Push a new state
    window.history.pushState(null, '', window.location.href);
    // Replace the state
    window.history.replaceState(null, '', window.location.href);
    
    // Prevent the back button
    window.onpopstate = function(event) {
        window.history.pushState(null, '', window.location.href);
    };
</script>

<body>

<section class="bg-primary py-3 py-md-5 py-xl-8">
    <div class="container">
        <div class="row gy-4 align-items-center">
        <div class="col-12 col-md-6 col-xl-7">
            <div class="d-flex justify-content-center text-bg-primary">
                <div class="col-12 col-xl-9">
                    <hr class="border-primary-subtle mb-4">
                    <h1 class="h1 mb-4">591 房源即時通知</h1>
                </div>
            </div>
            <div class="col-12 col-md-6 col-xl-5">
                <div class="card border-0 rounded-4">
                  <div class="card-body p-3 p-md-4 p-xl-5">
                    <div class="row">
                      <div class="col-12">
                        <div class="mb-4">
                          <h3>成功登入！</h3>
                        </div>
                      </div>
                    </div>
                    <div class="row gy-3 overflow-hidden">
                        <div class="col-12">
                          <div class="d-grid">
                            <button onclick=backToHome() class="btn btn-primary btn-lg">回到首頁</button>
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
        </div>
        <div class="col-12 col-md-6 col-xl-5 text-bg-primary">
            <div class="text-endx">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-grip-horizontal" viewBox="0 0 16 16">
                    <path d="M2 8a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg>
                </div>
        </div>
        <!-- Footer -->
        <footer class="text-center text-lg-start text-white">
        <!-- Grid container -->
          <div class="container p-4 pb-0">  
            <img class="img-fluid rounded mb-4" loading="lazy" src="{% static 'header.jpg' %}">
          </div>
          <hr class="mb-4" />
          <!-- Google -->
          <a
              class="btn btn-outline-light btn-floating m-1"
              href="mailto:r11323007@ntu.edu.tw"
              role="button"
              ><i class="fa fa-google"></i
              ></a>

          <!-- Github -->
          <a
              class="btn btn-outline-light btn-floating m-1"
              href="https://github.com/johnny890122/line_591_notifications" 
              target="_blank"
              role="button"
              ><i class="fa fa-github"></i
              ></a>
        </div>
    </div>
</section>
</body>
</html>

line_591_notifications/templates/isLogout.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% load static %}
</head>

<script>
    function backToLogin() {
        localStorage.removeItem('userId');
        window.location.href = "{{base_url}}/login";
    }
</script>

<body>
<section class="bg-primary py-3 py-md-5 py-xl-8">
    <div class="container">
        <div class="row gy-4 align-items-center">
        <div class="col-12 col-md-6 col-xl-7">
            <div class="d-flex justify-content-center text-bg-primary">
                <div class="col-12 col-xl-9">
                    <hr class="border-primary-subtle mb-4">
                    <h1 class="h1 mb-4">591 房源即時通知</h1>
                </div>
            </div>
            <div class="col-12 col-md-6 col-xl-5">
                <div class="card border-0 rounded-4">
                  <div class="card-body p-3 p-md-4 p-xl-5">
                    <div class="row">
                      <div class="col-12">
                        <div class="mb-4">
                          <h3>已登出！</h3>
                        </div>
                      </div>
                    </div>
                    <div class="row gy-3 overflow-hidden">
                        <div class="col-12">
                          <div class="d-grid">
                            <button onclick=backToLogin() class="btn btn-primary btn-lg">重新登入</button>
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
        </div>
        <div class="col-12 col-md-6 col-xl-5 text-bg-primary">
            <div class="text-endx">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-grip-horizontal" viewBox="0 0 16 16">
                    <path d="M2 8a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg>
                </div>
        </div>
        <!-- Footer -->
        <footer class="text-center text-lg-start text-white">
        <!-- Grid container -->
          <div class="container p-4 pb-0">  
            <img class="img-fluid rounded mb-4" loading="lazy" src="{% static 'header.jpg' %}">
          </div>
          <hr class="mb-4" />
          <!-- Google -->
          <a
              class="btn btn-outline-light btn-floating m-1"
              href="mailto:r11323007@ntu.edu.tw"
              role="button"
              ><i class="fa fa-google"></i
              ></a>

          <!-- Github -->
          <a
              class="btn btn-outline-light btn-floating m-1"
              href="https://github.com/johnny890122/line_591_notifications" 
              target="_blank"
              role="button"
              ><i class="fa fa-github"></i
              ></a>
        </div>
    </div>
</section>

</body>

</html>

line_591_notifications/templates/loginInfo.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<h1>成功登入</h1>

<body>
    <button onclick=backToHome()>回到首頁</button>
</body>

<script>
    localStorage.setItem('userId', '{{user_id}}');
    function backToHome() {
        window.location.href = "{{base_url}}/"
    }
</script>
</body>
</html>